import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillBehanceSquare, AiFillLinkedin, AiFillInstagram} from "react-icons/ai";
import Image from "next/legacy/image";
import deved from "../public/profile-pic.jpeg";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from "react";

export default function Home(){
    const [darkMode, setDarkMode] = useState(false);
    return(
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Matheus Pisani Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
                <section className="min-h-screen">
                <nav className="py-10 mb-12 flex justify-between dark:text-white">
                <h1 className="text-sm font-poppins">DESENVOLVIDO POR MATHEUS</h1>
                <ul className="flex items-center">
                    <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
                        <li>
                            <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
                        </li>
                </ul>
                </nav>
                <div className="text-center p-10 py-10">
                    <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:tex-6xl">Matheus Pisani</h2>
                    <h3 className="text-2xl pyy-2 md:text-3xl dark:text-gray-100">UX/UI Designer Júnior e Desenvolvedor.</h3>
                    <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
                    <Image src={deved} layout="fill" objectFit="cover" />
                    </div>
                </div>
                <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
                    <AiFillBehanceSquare />
                    <AiFillLinkedin />
                    <AiFillInstagram />
                </div>
                <div className="text-center p-10 py-10">
                    <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 mx-auto">Graduando em Gestão e Tecnologia da Informação, com foco no desenvolvimento de estudos e prototipações nas áreas de User Experience e User Interface, engajado em proporcionar experiências que agreguem valor positivo para as pessoas usuárias e consequentemente para o negócio. Motivado pela vontade de aprender e fazer a diferença. Previamente atuei como profissional da área de atendimento e experiência do cliente no setor hoteleiro, com vivência no treinamento e capacitação de colaboradores, padronização de processos, gestão de equipes e processos de aquisição de novos talentos. Minha motivação como profissional é a troca de experiências e o aprendizado constante em busca de atingir os melhores resultados. Para chegar a estes objetivos busco investir em uma formação contínua e networking.</p>
                </div>
                </section>

                <section>
                    <div>
                        <h3 className="text-3xl py-1 text-teal-600 font-medium dark:text-teal-400">O que tenho buscado!</h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Uma oportunidade de desenvolvimento e aprendizado profissional dentro da área de Tecnologia
                         da Informação. Acredito que um programa de estágio ou uma vaga júnior pode me proporcionar uma experiência prática de trabalho em um ambiente real, com a chance de aprender
                         com profissionais experientes, que poderão me orientar e compartilhar seus conhecimentos e experiências. O que permitirá aplicar e desenvolver as habilidades aprendidas na 
                         faculdade, proporcionando experiência prática e diversas oportunidades de aprendizado que irão me proporcionar crecimento profissional e pessoal.</p>
                    </div>
                    <div className="lg:flex gap-10">
                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark: bg-white flex-1">
                            <Image src={design} width={100} height={100}/>
                            <h3 className="text-lg font-medium pt-8 pb-2">Design UX / UI</h3>
                            <p className="py-2">
                                Estou engajado na criação designs elegantes e funcionais, buscando aplicar as teorias do design em projetos e cursos práticos para aprimorar minha experiência.
                            </p>
                            <h4 className="py-4 text-teal-600">Ferramentas Utilizadas</h4>
                            <p className="text-gray-800 py-1">Figma</p>
                            <p className="text-gray-800 py-1">AdobeXD</p>
                            <p className="text-gray-800 py-1">Photoshop</p>
                            <p className="text-gray-800 py-1">CorelDRAW</p>
                        </div>

                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark: bg-white flex-1">
                            <Image src={code} width={100} height={100}/>
                            <h3 className="text-lg font-medium pt-8 pb-2">Desenvolvimento</h3>
                            <p className="py-2">
                            Embora ainda esteja no início da minha jornada como desenvolvedor júnior, estou comprometido em aprender continuamente e aprimorar minhas habilidades. 
                            </p>
                            <h4 className="py-4 text-teal-600">Ferramentas Utilizadas</h4>
                            <p className="text-gray-800 py-1">HTML</p>
                            <p className="text-gray-800 py-1">JavaScript</p>
                            <p className="text-gray-800 py-1">CSS</p>
                            <p className="text-gray-800 py-1">Git e GitHub</p>
                        </div>

                        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark: bg-white flex-1">
                            <Image src={consulting} width={100} height={100}/>
                            <h3 className="text-lg font-medium pt-8 pb-2">Hobbies</h3>
                            <p className="py-2">
                                Além do meu entusiasmo pelo desenvolvimento de software, também sou um entusiasta de diversos hobbies. Acredito que essas atividades contribuem para o meu crescimento pessoal e profissional.
                            </p>
                            <h4 className="py-4 text-teal-600">Atividade</h4>
                            <p className="text-gray-800 py-1">Corrida e Musculação</p>
                            <p className="text-gray-800 py-1">Leitura</p>
                            <p className="text-gray-800 py-1">Aprendizado Contínuo</p>
                        </div>
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className="text-3xl py-1 text-teal-600 font-medium dark:text-teal-400">Portfólio</h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Estou entusiasmado em compartilhar mais detalhes sobre os projetos de UX/UI do meu portfólio. Além disso, destaco minha capacidade de aprender rapidamente, adaptar-me a novos desafios e trabalhar de forma colaborativa em equipe.</p>
                    </div>
                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web1}/></div>
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web2}/></div>
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web3}/></div>
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web4}/></div>
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web5}/></div>
                        <div className="basis-1/3 flex-1"><Image className="rounded-lg object-cover"width={"100%"} height={"100%"} layout="responsive" src={web6}/></div>
                    </div>
                </section>
            </main>

        </div>
    );
}